# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p8Wz1pdosx41evwmEpKPLbBmbNOf4wkm

**STEP 1: DATA COLLECTION**
"""

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

# 1. Load the Iris dataset directly from scikit-learn
iris = load_iris(as_frame=True)

# 2. Extract feature matrix (X) and target array (y)
df = iris.frame

# 3. Quick inspection
print(f"Dataset Shape: {df.shape} (Rows x Columns)\n")
print("Target Classes:", iris.target_names)
print("\nFirst 5 rows of the dataset:")
df.head()

"""### **STEP 2-DATA CLEANING.**"""

# 1. Check Data Types and Non-Null Counts
print("--- 1. Data Structure Info ---")
df.info()

# 2. Check for Missing Values
print("\n--- 2. Missing Values Count per Feature ---")
print(df.isnull().sum())

# 3. Check for Duplicate Rows
duplicates = df.duplicated().sum()
print(f"\n--- 3. Duplicate Rows Found: {duplicates} ---")

# If duplicates exist, remove them to keep data clean
if duplicates > 0:
    df = df.drop_duplicates().reset_index(drop=True)
    print("Duplicates removed! New shape:", df.shape)

# 4. Statistical Summary
print("\n--- 4. Summary Statistics ---")
print(df.describe().T[['min', 'mean', '50%', 'max']])

"""### **STEP 3: DATA PREPROCESSING**"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Separate features (X) and target variable (y)
X = df.drop(columns=['target'])
y = df['target']

# 2. Train-Test Split (80% Train, 20% Test) with Stratification
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 3. Feature Scaling using StandardScaler
scaler = StandardScaler()

# Fit ONLY on training data, then transform both train and test sets
X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X.columns,
    index=X_test.index
)

# 4. Verification
print(f"Training set shape: {X_train_scaled.shape}")
print(f"Test set shape:     {X_test_scaled.shape}\n")
print("Target class distribution in test set (balanced):")
print(y_test.value_counts())

"""### **STEP 4: FEATURE ENGINEERING & SELECTION**"""

def engineer_iris_features(data):
    df_feat = data.copy()

    # 1. Shape Ratios
    df_feat['petal_ratio'] = df_feat['petal length (cm)'] / df_feat['petal width (cm)']
    df_feat['sepal_ratio'] = df_feat['sepal length (cm)'] / df_feat['sepal width (cm)']

    # 2. Area Approximations
    df_feat['petal_area'] = df_feat['petal length (cm)'] * df_feat['petal width (cm)']

    # Handle possible division issues
    df_feat.replace([np.inf, -np.inf], np.nan, inplace=True)
    df_feat.fillna(df_feat.median(), inplace=True)

    return df_feat

# Create engineered features on raw train and test splits
X_train_eng = engineer_iris_features(X_train)
X_test_eng = engineer_iris_features(X_test)

# Scale all features (original + new engineered ones)
scaler_eng = StandardScaler()
X_train_eng_scaled = pd.DataFrame(
    scaler_eng.fit_transform(X_train_eng),
    columns=X_train_eng.columns,
    index=X_train_eng.index
)
X_test_eng_scaled = pd.DataFrame(
    scaler_eng.transform(X_test_eng),
    columns=X_test_eng.columns,
    index=X_test_eng.index
)

# Feature Selection Check: Correlation with target species
train_full = X_train_eng_scaled.copy()
train_full['target'] = y_train

correlations = train_full.corr()['target'].sort_values(ascending=False)

print("--- Correlation of Engineered Features with Target Species ---")
print(correlations)

"""### **STEP 5: MODEL SELECTION**"""

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Initialize classification models
models = {
    "Logistic Regression": LogisticRegression(random_state=42),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=5),
    "Support Vector Machine": SVC(kernel='rbf', random_state=42),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=42)
}

print("Selected Classification Candidates:")
for name in models.keys():
    print(f" - {name}")

"""### **STEP 6: MODEL TRAINING**"""

from sklearn.model_selection import cross_val_score

# 1. Train and evaluate Logistic Regression
lr_model = models["Logistic Regression"]
lr_model.fit(X_train_eng_scaled, y_train)
lr_scores = cross_val_score(lr_model, X_train_eng_scaled, y_train, cv=5, scoring='accuracy')
print(f"Logistic Regression Mean CV Accuracy: {lr_scores.mean():.4f}")

# 2. Train and evaluate K-Nearest Neighbors
knn_model = models["K-Nearest Neighbors"]
knn_model.fit(X_train_eng_scaled, y_train)
knn_scores = cross_val_score(knn_model, X_train_eng_scaled, y_train, cv=5, scoring='accuracy')
print(f"K-Nearest Neighbors Mean CV Accuracy: {knn_scores.mean():.4f}")

# 3. Train and evaluate Support Vector Machine
svm_model = models["Support Vector Machine"]
svm_model.fit(X_train_eng_scaled, y_train)
svm_scores = cross_val_score(svm_model, X_train_eng_scaled, y_train, cv=5, scoring='accuracy')
print(f"Support Vector Machine Mean CV Accuracy: {svm_scores.mean():.4f}")

# 4. Train and evaluate Random Forest
rf_model = models["Random Forest"]
rf_model.fit(X_train_eng_scaled, y_train)
rf_scores = cross_val_score(rf_model, X_train_eng_scaled, y_train, cv=5, scoring='accuracy')
print(f"Random Forest Mean CV Accuracy:        {rf_scores.mean():.4f}")

"""### **STEP 7: MODEL EVALUATION**"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1. Generate predictions on the unseen test set
pred_lr = lr_model.predict(X_test_eng_scaled)
pred_knn = knn_model.predict(X_test_eng_scaled)
pred_svm = svm_model.predict(X_test_eng_scaled)
pred_rf = rf_model.predict(X_test_eng_scaled)

# Helper function to print clean metrics
def evaluate_classifier(name, y_true, y_pred):
    print(f"=== {name} ===")
    print(f"Test Accuracy: {accuracy_score(y_true, y_pred):.4f}\n")
    print("Classification Report:")
    print(classification_report(y_true, y_pred, target_names=iris.target_names))
    print("Confusion Matrix:")
    print(confusion_matrix(y_true, y_pred))
    print("-" * 45 + "\n")

# 2. Evaluate all candidate models
evaluate_classifier("Logistic Regression", y_test, pred_lr)
evaluate_classifier("K-Nearest Neighbors", y_test, pred_knn)
evaluate_classifier("Support Vector Machine", y_test, pred_svm)
evaluate_classifier("Random Forest", y_test, pred_rf)

"""### **STEP 8: HYPERPARAMETER TUNING**"""

from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

# 1. Define the grid of parameters for SVM
param_grid = {
    'C': [0.1, 1, 10, 100],            # Penalty parameter
    'gamma': ['scale', 'auto', 0.01, 0.1, 1], # Kernel coefficient
    'kernel': ['rbf', 'linear']        # Kernel types
}

# 2. Set up GridSearchCV with 5-fold cross-validation
svm_grid = GridSearchCV(
    estimator=SVC(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

# 3. Fit the search on our scaled training data
print("Tuning SVM hyperparameters...")
svm_grid.fit(X_train_eng_scaled, y_train)

# 4. Extract the best model and parameters
best_svm_model = svm_grid.best_estimator_

print("\nBest Parameters Found:")
print(svm_grid.best_params_)

# 5. Evaluate the tuned model on the unseen test set
tuned_pred = best_svm_model.predict(X_test_eng_scaled)
tuned_accuracy = accuracy_score(y_test, tuned_pred)

print(f"\n--- Tuned SVM Test Accuracy: {tuned_accuracy:.4f} ---")

"""### **STEP 9: DEPLOYMENT**"""

import joblib

# 1. Save the best tuned model and feature scaler with compression
joblib.dump(best_svm_model, 'iris_svm_model.pkl', compress=3)
joblib.dump(scaler_eng, 'iris_scaler.pkl', compress=3)

print("✓ Iris Model and Scaler successfully saved to disk!")

# 2. Simulate loading the saved model and scaler in a production environment
loaded_svm = joblib.load('iris_svm_model.pkl')
loaded_scaler = joblib.load('iris_scaler.pkl')

# 3. Test prediction with a single test sample
sample_data = X_test_eng_scaled.iloc[[0]]
predicted_class = loaded_svm.predict(sample_data)[0]
predicted_species = iris.target_names[predicted_class]
actual_species = iris.target_names[y_test.iloc[0]]

print("\n--- Production Test Run ---")
print(f"Predicted Species: {predicted_species}")
print(f"Actual Species:    {actual_species}")

"""### **STEP 10: MONITORING & MAINTENANCE**"""

# 1. Monitor Prediction Class Distribution
train_class_dist = y_train.value_counts(normalize=True)
test_predictions = pd.Series(tuned_pred).value_counts(normalize=True)

print("--- 1. Prediction Distribution Comparison ---")
print("Training Ground Truth Distribution:")
print(train_class_dist.to_dict())
print("\nProduction Prediction Distribution:")
print(test_predictions.to_dict())

# 2. Accuracy Monitoring & Automated Retrain Trigger
current_accuracy = accuracy_score(y_test, tuned_pred)
ACCURACY_THRESHOLD = 0.90  # Alert if production accuracy drops below 90%

print("\n--- 2. Production Performance Trigger ---")
print(f"Current Production Accuracy: {current_accuracy * 100:.2f}%")

if current_accuracy < ACCURACY_THRESHOLD:
    print("⚠️ ALERT: Model accuracy dropped below threshold! Retraining required.")
else:
    print("✅ STATUS: Model operating within acceptable limits. No action needed.")

